<?php
/**
 * SlideGallery - custom product gallery template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 * @var $escaper \Magento\Framework\Escaper
 */
// @codingStandardsIgnoreFile
?>

<?php
$galleryImagesJson = $block->getGalleryImagesJson();
$galleryImages = json_decode($galleryImagesJson);

$imageWidth = $block->getImageAttribute('product_page_image_medium', 'width');
$imageHeight = $block->getImageAttribute('product_page_image_medium', 'height');

$imageFullWidth = $block->getImageAttribute('product_page_image_large', 'width');
$imageFullHeight = $block->getImageAttribute('product_page_image_large', 'height');

$imageSmallWidth = $block->getImageAttribute('product_page_image_small', 'width');
$imageSmallHeight = $block->getImageAttribute('product_page_image_small', 'height');

$videoType = $block->getVar('video_slide/type', 'MageSuite_ProductSlideGallery');

$loaderImage = 'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=';
?>

<div class="cs-slide-gallery" data-gallery-role="gallery-placeholder" data-image-params='{
        "imageMimeType": "", <?= /* backwards compatibility, we don't need it anymore */ ?>
        "imageWidth": <?= /* @noEscape */ $imageWidth; ?>,
        "imageHeight": <?= /* @noEscape */ $imageHeight; ?>,
        "imageFullWidth": <?= /* @noEscape */ $imageFullWidth; ?>,
        "imageFullHeight": <?= /* @noEscape */ $imageFullHeight; ?>,
        "imageSmallWidth": <?= /* @noEscape */ $imageSmallWidth; ?>,
        "imageSmallHeight": <?= /* @noEscape */ $imageSmallHeight; ?>,
        "loaderImage": "<?= /* @noEscape */ $loaderImage; ?>",
        "initialGalleryImages": <?= $escaper->escapeHtmlAttr($galleryImagesJson); ?>
    }' data-item-count="<?= $escaper->escapeHtmlAttr(count($galleryImages)) ?>">
    <div data-role="focusable-start"></div>
    <div class="cs-slide-gallery__wrapper">
        <div class="cs-slide-gallery__slides-wrapper" tabindex="0" role="button">
        <ul class="cs-slide-gallery__slides">
            <?php $i = 1; foreach ($galleryImages as $image) : ?>
                <?php if ($image->type === "video") : ?>
                    <li class="cs-slide-gallery__slide cs-slide-gallery__slide--video">
                        <div class="cs-slide-gallery__picture-wrapper">
                            <picture class="cs-slide-gallery__picture cs-slide-gallery__picture--video">
                                <div data-video-teaser='{"url": "<?= $escaper->escapeUrl($image->videoUrl) ?>","type": "<?= $escaper->escapeHtml($videoType) ?>"}'>
                                    <?= /* @noEscape */ $block->getChildHtml("consent_info"); ?>
                                </div>
                                <img
                                    src="<?= /* @noEscape */ $loaderImage ?>"
                                    data-src="<?= $escaper->escapeUrl($image->img) ?>"
                                    width="<?= $escaper->escapeHtmlAttr($imageWidth) ?>"
                                    height="<?= $escaper->escapeHtmlAttr($imageHeight) ?>"
                                    alt="<?= $escaper->escapeHtmlAttr($image->caption) ?>"
                                    class="cs-slide-gallery__img lazyload"
                                >
                            </picture>
                        </div>
                    </li>
                <?php else : ?>
                    <li class="cs-slide-gallery__slide">
                        <div class="cs-slide-gallery__picture-wrapper">
                            <?php if ($i < 2) : ?>
                                <picture class="cs-slide-gallery__picture cs-slide-gallery__picture--base">
                                    <img
                                        src="<?= $escaper->escapeUrl($image->img) ?>"
                                        width="<?= $escaper->escapeHtmlAttr($imageWidth) ?>"
                                        height="<?= $escaper->escapeHtmlAttr($imageHeight) ?>"
                                        alt="<?= $escaper->escapeHtmlAttr($image->caption) ?>"
                                        class="cs-slide-gallery__img"
                                        fetchpriority="high"
                                        loading="eager"
                                    >
                                </picture>
                            <?php else : ?>
                                <picture class="cs-slide-gallery__picture cs-slide-gallery__picture--base">
                                    <img
                                        src="<?= /* @noEscape */ $loaderImage ?>"
                                        data-src="<?= $escaper->escapeUrl($image->img) ?>"
                                        width="<?= $escaper->escapeHtmlAttr($imageWidth) ?>"
                                        height="<?= $escaper->escapeHtmlAttr($imageHeight) ?>"
                                        alt="<?= $escaper->escapeHtmlAttr($image->caption) ?>"
                                        class="cs-slide-gallery__img lazyload"
                                    >
                                </picture>
                            <?php endif; ?>

                            <picture class="cs-slide-gallery__picture cs-slide-gallery__picture--full">
                            <img
                                src="<?= /* @noEscape */ $loaderImage ?>"
                                data-src="<?= $escaper->escapeUrl($image->full) ?>"
                                width="<?= $escaper->escapeHtmlAttr($imageFullWidth) ?>"
                                height="<?= $escaper->escapeHtmlAttr($imageFullHeight) ?>"
                                alt="<?= $escaper->escapeHtmlAttr($image->caption) ?>"
                                class="cs-slide-gallery__img"
                            >
                        </picture>
                        </div>
                    </li>
                <?php endif; ?>
            <?php $i++; endforeach ?>
        </ul>
        </div>

        <div class="cs-slide-gallery__actions">
            <button class="cs-slide-gallery__close" type="button" aria-label="<?= $escaper->escapeHtml(__('Close')) ?>"></button>
            <button class="cs-slide-gallery__zoom" type="button" aria-label="<?= $escaper->escapeHtml(__('Zoom')) ?>"></button>
            <button class="cs-slide-gallery__unzoom" type="button" aria-label="<?= $escaper->escapeHtml(__('Unzoom')) ?>"></button>
        </div>
        <?php if (count($galleryImages) > 1) : ?>
        <button class="cs-slide-gallery__nav cs-slide-gallery__nav--prev" type="button" aria-label="<?= $escaper->escapeHtml(__('Previous')) ?>">
            <?= $block->getChildHtml('slide.gallery.button.arrow.prev'); ?>
        </button>
        <button class="cs-slide-gallery__nav cs-slide-gallery__nav--next" type="button" aria-label="<?= $escaper->escapeHtml(__('Next')) ?>">
            <?= $block->getChildHtml('slide.gallery.button.arrow.next'); ?>
        </button>
        <?php endif; ?>

        <div class="cs-slide-gallery__pagination-wrapper">
            <div class="cs-slide-gallery__pagination">
                <?php foreach ($galleryImages as $image) : ?>
                    <?php if ($image->type === "video") : ?>
                        <div class="cs-slide-gallery__thumb cs-slide-gallery__thumb--video" tabindex="0" role="button">
                    <?php else : ?>
                        <div class="cs-slide-gallery__thumb" tabindex="0" role="button">
                    <?php endif; ?>
                            <img class="cs-slide-gallery__thumb-img" src="<?= $escaper->escapeUrl($image->thumb) ?>" width="<?= $escaper->escapeHtmlAttr($imageSmallWidth) ?>" height="<?= $escaper->escapeHtmlAttr($imageSmallHeight) ?>" alt="<?= $escaper->escapeHtmlAttr($image->caption) ?>" loading="lazy"/>
                        </div>
                <?php endforeach ?>
            </div>

            <button class="cs-slide-gallery__thumb-nav cs-slide-gallery__thumb-nav--prev" type="button" aria-label="<?= $block->escapeHtmlAttr(__('Previous')) ?>" disabled>
                <?= $block->getChildHtml('slide.gallery.thumb.button.arrow.prev'); ?>
            </button>
            <button class="cs-slide-gallery__thumb-nav cs-slide-gallery__thumb-nav--next" type="button" aria-label="<?= $block->escapeHtmlAttr(__('Next')) ?>" disabled>
                <?= $block->getChildHtml('slide.gallery.thumb.button.arrow.next'); ?>
            </button>
        </div>
    </div>
    <div class="load indicator" style="display: none;"></div>
    <div data-role="focusable-end"></div>
</div>
